#!/usr/bin/env Rscript
options(java.parameters = "-Xmx8000m")

library(ENMTools)
library(dismo)

northerncardinal.path <- paste("/home/dnjacks4/Birds/ebird_noca_AprMay_2016_2021_latlong_new.csv", sep=',')
pyrrhuloxia.path <- paste("/home/dnjacks4/Birds/ebird_pyrr_AprMay_2016_2021_latlong_new.csv", sep=',')
env.files <- list.files(path = "/home/dnjacks4/Tucson/", full.names = TRUE)
output.file <- paste("/home/dnjacks4/maxentoutput_dec18.txt")

env <- stack(env.files)
env <- setMinMax(env)

env[[1]][is.na(env[[1]])] <- 0
env[[2]][is.na(env[[2]])] <- 0
env[[3]][is.na(env[[3]])] <- 0
env[[4]][is.na(env[[4]])] <- 0
env[[5]][is.na(env[[5]])] <- 0
env[[6]][is.na(env[[6]])] <- 0
env[[7]][is.na(env[[7]])] <- 0
env[[8]][is.na(env[[8]])] <- 0
env[[9]][is.na(env[[9]])] <- 0
env[[10]][is.na(env[[10]])] <- 0
env[[11]][is.na(env[[11]])] <- 0
env[[12]][is.na(env[[12]])] <- 0
env[[13]][is.na(env[[13]])] <- 0
env[[14]][is.na(env[[14]])] <- 0
env[[15]][is.na(env[[15]])] <- 0

env <- check.env(env)
crs(env) <- "+proj=longlat +datum=WGS84 +no_defs"


pyrrhuloxia <- enmtools.species()
pyrrhuloxia <- enmtools.species(species.name = "Pyrrhuloxia",
                            presence.points = read.csv(pyrrhuloxia.path))
pyrrhuloxia$range <- background.raster.buffer(pyrrhuloxia$presence.points, 50000, mask = env)
pyrrhuloxia$background.points <- background.points.buffer(points = pyrrhuloxia$presence.points, radius = 20000, n = 1000, mask = env[[1]])


northerncardinal <- enmtools.species()
northerncardinal <- enmtools.species(species.name = "Northern Cardinal",
                            presence.points = read.csv(northerncardinal.path))
northerncardinal$range <- background.raster.buffer(northerncardinal$presence.points, 50000, mask = env)
northerncardinal$background.points <- background.points.buffer(points = northerncardinal$presence.points, radius = 20000, n = 1000, mask = env[[1]])

pyrrhuloxia <- check.species(pyrrhuloxia)
northerncardinal <- check.species(northerncardinal)

corr_matrix <- raster.cor.matrix(env)

pdf(file = paste0("env_corr.pdf"), width = 20, height = 7, useDingbats=FALSE)
print(raster.cor.plot(env))
dev.off()

pyrrhuloxia.mx <- enmtools.maxent(pyrrhuloxia, env)
northerncardinal.mx <- enmtools.maxent(northerncardinal, env)
env_names <- names(env)

for (x in env_names){
  print(x)
}

for (x in env_names){
  pdf(file = paste0(x,".pdf"), width = 20, height = 7, useDingbats=FALSE)
  print(marginal.plots(pyrrhuloxia.mx, env, x))
  dev.off()
}

cat(paste("pyrrhuloxia raster breadth"),file=paste0(output.file),sep="\n",append=TRUE)
cat(paste(raster.breadth(pyrrhuloxia.mx)),file=paste0(output.file),sep="\n",append=TRUE)

cat(paste("northern cardinal raster breadth"),file=paste0(output.file),sep="\n",append=TRUE)
cat(paste(raster.breadth(northerncardinal.mx)),file=paste0(output.file),sep="\n",append=TRUE)

cat(paste("raster overlap"),file=paste0(output.file),sep="\n",append=TRUE)
cat(paste(raster.overlap(pyrrhuloxia.mx, northerncardinal.mx)),file=paste0(output.file),sep="\n",append=TRUE)

cat(paste("env overlap tolerance 0.001"),file=paste0(output.file),sep="\n",append=TRUE)
cat(paste(env.overlap(pyrrhuloxia.mx, northerncardinal.mx, env, tolerance = .001)),file=paste0(output.file),sep="\n",append=TRUE)



# Hypothesis testing!!!!
id.mx <- identity.test(species.1 = pyrrhuloxia, species.2 = northerncardinal, env = env, type = "mx", nreps = 100)

cat(paste("identity test"),file=paste0(output.file),sep="\n",append=TRUE)
cat(paste(id.mx),file=paste0(output.file),sep="\n",append=TRUE)


# Background or similarity test
pyrrnoca.mx.asym <- background.test(species.1 = pyrrhuloxia, species.2 = northerncardinal, env = env, type = "mx", nreps = 1, test.type = "asymmetric")
# doesn't work

cat(paste("background test, pyrr noca mx asymmetric"),file=paste0(output.file),sep="\n",append=TRUE)
cat(paste(pyrrnoca.mx.asym),file=paste0(output.file),sep="\n",append=TRUE)


esp.sym.id <- enmtools.ecospat.id(pyrrhuloxia, northerncardinal, env, test.type = symmetric)
esp.asym.pn.id <- enmtools.ecospat.id(pyrrhuloxia, northerncardinal, env, test.type = asymmetric)
esp.asym.np.id <- enmtools.ecospat.id(pyrrhuloxia, northerncardinal, env, test.type = asymmetric)


rbl.mx <- rangebreak.linear(pyrrhuloxia, northerncardinal, env, type = "mx", nreps = 4)
rbb.mx <- rangebreak.blob(pyrrhuloxia, northerncardinal, env, type = "mx", nreps = 4)

library(help="ENMTools")
